language: php
php:
  - 5.4

before_script:
  # Set up the Github OAuth token.
  # Please change this if you fork this project.
  - sudo apt-get update 
  - composer self-update
  - composer --version
  - "mkdir -p ~/.composer"
  - cp .travis.composer.config.json ~/.composer/config.json
  # Install dependencies.
  - composer install --no-progress
  # Require drupal/core.
  - composer require drupal/core 8.0.*@dev
  - ls
  - pwd

script:
  # Our PHPUnit tests simply try to use classes which exist in Drupal core.
  - ls -lR
  - pwd