language: php

php:
  - 5.4

before_install:
  - sudo apt-get update 
  - composer self-update
  - sudo apt-get install -y --force-yes php5-cgi php5-mysql sqlite3 php5-sqlite php5-gd 
  - composer global require drupal/drupal-extension:"~3.0"  
  - composer global require drush/drush:dev-master
  - export PATH="$HOME/.composer/vendor/bin:$PATH"
  - mkdir web
  - cd web
  - drush qd mydrupal --core=drupal-8.0.x --dev --no-cache --yes --profile=standard --no-server --account-mail='a@b.com' --account-name=admin --account-pass=password --site-name=boo  
  - cd mydrupal/drupal-8.0.x
  - drush runserver --server=builtin 8080 --strict=0 &
  - until netstat -an 2>/dev/null | grep '8080.*LISTEN'; do sleep 0.2; done
  - cd modules
  - git clone https://github.com/mohankumargupta/mentionsdrupal8module.git mentions

before_script:
  - drush en -y mentions
  - drush pm-list --pipe --type=module --status=enabled --no-core | grep -x mentions
  - cd mentions

script:
  - behat -c ./behat.yml -dl
