language: php

php:
  - 5.4

before_install:
  - sudo apt-get update 
  - composer self-update
  - sudo apt-get install -y --force-yes php5-cgi php5-mysql sqlite3 php5-sqlite php5-gd 
  - composer require drupal/drupal-extension:"~3.0"  
  - composer global require drush/drush:dev-master
  - export PATH="$HOME/.composer/vendor/bin:$PATH"
  - mkdir web
  - cd web
  - drush qd mydrupal --core=drupal-8.0.x --dev --no-cache --yes --profile=standard --no-server --account-mail='a@b.com' --account-name=admin --account-pass=password --site-name=boo  
  - cd mydrupal/drupal-8.0.x
  - cd modules
  - git clone https://github.com/mohankumargupta/mentionsdrupal8module.git mentionsdrupal8module

before_script:
  - drush en -y mentions
  - drush pm-list --pipe --type=module --status=enabled --no-core | grep -x mentions

script:
  - cd $TRAVIS_BUILD_DIR
  - pwd