# @file
# .travis.yml 
#
# Template provided by https://github.com/LionsAd/drupal_ti.
#

language: php

sudo: false

php:
  - 5.5

matrix:
  fast_finish: true

env:
  global:
    - PATH="$PATH:$HOME/.composer/vendor/bin"
    - DRUPAL_TI_MODULE_NAME="mentions"
    - DRUPAL_TI_ENVIRONMENT="drupal-8"
    - DRUPAL_TI_DB="drupal_travis_db"
    - DRUPAL_TI_DB_URL="mysql://root:@127.0.0.1/drupal_travis_db"
    - DRUPAL_TI_WEBSERVER_URL="http://127.0.0.1"
    - DRUPAL_TI_WEBSERVER_PORT="8080"
    - DRUPAL_TI_BEHAT_DIR="./tests/behat"
    - DRUPAL_TI_BEHAT_ARGS=""
    - DRUPAL_TI_BEHAT_YML="behat.yml"
    - DRUPAL_TI_BEHAT_SCREENSIZE_COLOR="1280x1024x16"
    # The version of selenium that should be used.
    - DRUPAL_TI_BEHAT_SELENIUM_VERSION="2.48.2"
    # Set DRUPAL_TI_BEHAT_DRIVER to "selenium" to use "firefox" or "chrome" here.
    - DRUPAL_TI_BEHAT_DRIVER="selenium"

    # PHPUnit specific commandline arguments.
    - DRUPAL_TI_PHPUNIT_ARGS=""
    # Specifying the phpunit-core src/ directory is useful when e.g. a vendor/
    # directory is present in the module directory, which phpunit would then
    # try to find tests in. This option is relative to $TRAVIS_BUILD_DIR.
    #- DRUPAL_TI_PHPUNIT_CORE_SRC_DIRECTORY="./tests/src"

    # Code coverage via coveralls.io
    - DRUPAL_TI_COVERAGE="satooshi/php-coveralls:0.6.*"
    # This needs to match your .coveralls.yml file.
    - DRUPAL_TI_COVERAGE_FILE="build/logs/clover.xml"

    # Debug options
    #- DRUPAL_TI_DEBUG="-x -v"
    # Set to "all" to output all files, set to e.g. "xvfb selenium" or "selenium",
    # etc. to only output those channels.
    #- DRUPAL_TI_DEBUG_FILE_OUTPUT="selenium xvfb webserver"

  matrix:
    # [[[ SELECT ANY OR MORE OPTIONS ]]]
    #- DRUPAL_TI_RUNNERS="phpunit"
    #- DRUPAL_TI_RUNNERS="simpletest"
    #- DRUPAL_TI_RUNNERS="behat"
    - DRUPAL_TI_RUNNERS="phpunit behat"
    # Use phpunit-core to test modules with phpunit with Drupal 8 core.
    #- DRUPAL_TI_RUNNERS="phpunit-core"

mysql:
  database: drupal_travis_db
  username: root
  encoding: utf8

before_install:
  - composer self-update
  - cd ./tests
  - composer init
  - composer global require "lionsad/drupal_ti:dev-master"
  - drupal-ti before_install

install:
  - drupal-ti install

before_script:
  - drupal-ti before_script

script:
  - ls
  - drupal-ti script

after_script:
  - drupal-ti after_script

notifications:
  email: false
