# @file
# .travis.yml - Drupal for Travis CI Integration
#
# Template provided by https://github.com/LionsAd/drupal_ti.
#
# Based for simpletest upon:
#   https://github.com/sonnym/travis-ci-drupal-module-example

language: php
sudo: false
php:
  - 5.5
env:
  global:
    - PATH="$PATH:$HOME/.composer/vendor/bin"
    - DRUPAL_TI_MODULE_NAME="mentionsdrupal8module"
    - DRUPAL_TI_SIMPLETEST_GROUP="mentionsdrupal8module"
    - DRUPAL_TI_ENVIRONMENT="drupal-8"
    - DRUPAL_TI_DB="drupal_travis_db"
    - DRUPAL_TI_DB_URL="mysql://root:@127.0.0.1/drupal_travis_db"
    - DRUPAL_TI_WEBSERVER_URL="http://127.0.0.1"
    - DRUPAL_TI_WEBSERVER_PORT="8080"
    - DRUPAL_TI_SIMPLETEST_ARGS="--verbose --color --concurrency 4 --url $DRUPAL_TI_WEBSERVER_URL:$DRUPAL_TI_WEBSERVER_PORT"
    - DRUPAL_TI_BEHAT_DIR="./tests/behat"
    - DRUPAL_TI_BEHAT_ARGS=""
    - DRUPAL_TI_BEHAT_YML="behat.yml.dist"
    - DRUPAL_TI_BEHAT_SCREENSIZE_COLOR="1280x1024x16"
    - DRUPAL_TI_BEHAT_SELENIUM_VERSION="2.44"
    - DRUPAL_TI_BEHAT_DRIVER="selenium"
    - DRUPAL_TI_BEHAT_BROWSER="firefox"
    - DRUPAL_TI_PHPUNIT_ARGS=""
    - DRUPAL_TI_COVERAGE="satooshi/php-coveralls:0.6.*"
    - DRUPAL_TI_COVERAGE_FILE="build/logs/clover.xml"

    # Debug options
    #- DRUPAL_TI_DEBUG="-x -v"
    # Set to "all" to output all files, set to e.g. "xvfb selenium" or "selenium",
    # etc. to only output those channels.
    #- DRUPAL_TI_DEBUG_FILE_OUTPUT="selenium xvfb webserver"

  matrix:
    # [[[ SELECT ANY OR MORE OPTIONS ]]]
    - DRUPAL_TI_RUNNERS="phpunit-core"
    #- DRUPAL_TI_RUNNERS="behat"
    #- DRUPAL_TI_RUNNERS="behat"
    #- DRUPAL_TI_RUNNERS="phpunit simpletest behat"

mysql:
  database: drupal_travis_db
  username: root
  encoding: utf8

before_install:
  - pwd
  - ls
  - composer self-update
  - composer global require "lionsad/drupal_ti:dev-master"
  #- composer global require "drupal/drupal-extension"
  - drupal-ti before_install

install:
  #- composer require "drupal/drupal-extension"    
  - drupal-ti install

before_script:
  #- drupal-ti --include .travis-before-script.sh
  - drupal-ti before_script

script:
  - drupal-ti script

after_script:
  - drupal-ti after_script

notifications:
  email: false
