# @file
# .travis.yml for Mentions Module.
#

language: php
sudo: false
php:
  - 5.5
env:
  global:
    - PATH="$PATH:$HOME/.composer/vendor/bin"
    - DRUPAL_TI_ENVIRONMENT="drupal-8"
    - DRUPAL_TI_MODULE_NAME="mentions"
    #- DRUPAL_TI_SCRIPT_DIR_BEFORE="./drupal_ti/before"
    - DRUPAL_TI_DB="drupal_travis_db"
    - DRUPAL_TI_DB_URL="mysql://root:@127.0.0.1/drupal_travis_db"
    - DRUPAL_TI_WEBSERVER_URL="http://127.0.0.1"
    - DRUPAL_TI_WEBSERVER_PORT="8080"
    - DRUPAL_TI_SIMPLETEST_ARGS="--verbose --color --concurrency 4 --url $DRUPAL_TI_WEBSERVER_URL:$DRUPAL_TI_WEBSERVER_PORT"
    - DRUPAL_TI_BEHAT_DIR="./tests/behat"
    - DRUPAL_TI_BEHAT_ARGS=""
    - DRUPAL_TI_BEHAT_YML="behat.yml"
    - DRUPAL_TI_BEHAT_SCREENSIZE_COLOR="1280x1024x16"
    - DRUPAL_TI_BEHAT_SELENIUM_VERSION="2.48.2"
    - DRUPAL_TI_BEHAT_DRIVER="phantomjs"
    - DRUPAL_TI_BEHAT_BROWSER="firefox"
    - DRUPAL_TI_PHPUNIT_ARGS=""
    - DRUPAL_TI_PHPUNIT_CORE_SRC_DIRECTORY="./tests/src"
    - DRUPAL_TI_COVERAGE="satooshi/php-coveralls:0.6.*"
    - DRUPAL_TI_COVERAGE_FILE="build/logs/clover.xml"
    - DRUPAL_TI_DEBUG_FILE_OUTPUT="selenium xvfb webserver hhvm"
    - DRUPAL_TI_CACHE_DIR="$HOME/drupal-ti-cache/"
    - DRUPAL_TI_LOAD_CACHE="1"
    - DRUPAL_TI_SAVE_CACHE="1"
    - DRUPAL_TI_CACHE_DIRS_HOME=".composer|.drush|.dist"
    - DRUPAL_TI_CACHE_DIRS_TRAVIS_BUILD_DIR="tests/vendor|tests/behat/vendor"

mysql:
  database: drupal_travis_db
  username: root
  encoding: utf8

before_install:
  - composer self-update
  - composer global require LionsAd/drupal_ti:dev-master
  - mkdir -p "$HOME/.composer/vendor/bin"
  - ln -sf $(pwd)/drupal-ti "$HOME/.composer/vendor/bin"
  - cd "./tests/$DRUPAL_TI_ENVIRONMENT/mentions"
  - export DRUPAL_TI_TESTS_DIR="$TRAVIS_BUILD_DIR"
  - export TRAVIS_BUILD_DIR=$(pwd)
  - ls
  - cd ./tests
  - drupal-ti before_install

install:
  - drupal-ti install

before_script:
  - drupal-ti --include ../scripts/test-include.sh
  - drupal-ti before_script

script:
  - drupal-ti script
  # Syncs $DRUPAL_TI_CACHE_DIRS_{*} to $DRUPAL_TI_CACHE_DIR/{*}
  # Has internal optimizations for .composer and .drush.
  - drupal-ti --save-cache TRAVIS_BUILD_DIR HOME

  # Do some manual caching as well
  - if [ "$DRUPAL_TI_SAVE_CACHE" = "1" ]; then rsync -a composer.{json,lock} "$DRUPAL_TI_CACHE_DIR"/TRAVIS_BUILD_DIR/tests/; fi

  # Delete composer generated files that screw up cache detection.
  - rm -f "$DRUPAL_TI_CACHE_DIR"/TRAVIS_BUILD_DIR/tests/.composer/vendor/composer/*.php
  - rm -f "$DRUPAL_TI_CACHE_DIR"/TRAVIS_BUILD_DIR/tests/.composer/vendor/autoload.php

  # Delete composer generated behat files that screw up cache detection.
  - rm -f "$DRUPAL_TI_CACHE_DIR"/TRAVIS_BUILD_DIR/tests/behat/.composer/vendor/composer/*.php
  - rm -f "$DRUPAL_TI_CACHE_DIR"/TRAVIS_BUILD_DIR/tests/behat/.composer/vendor/autoload.php

  # Tests for differences and touches a file if any are detected (optional).
  - du -sh "$DRUPAL_TI_CACHE_DIR"
  - drupal-ti --sync-cache

after_script:
  - drupal-ti after_script

notifications:
  email: false
