language: php

php:
  - 5.4

matrix:
  env:
    global:
    - DATABSE='drupal'
    - DB_USERNAME='root'
    - DB_ENCODE='utf8'

mysql:
  database: $DATABASE
  username: $DB_USERNAME
  encoding: $DB_ENCODE


before_install:
  - sudo apt-get update 
  - composer self-update
  - sudo apt-get install -y --force-yes php5-cgi php5-mysql
  - composer global require drush/drush:dev-master
  - export PATH="$HOME/.composer/vendor/bin:$PATH"
  - mkdir web
  - cd web
  - drush qd --core=drupal-8.0.x --dev --no-cache --root="$HOME/build/mohankumargupta/mentionsdrupal8module/web" --yes --profile=standard --no-server --account-mail='a@b.com' --account-name=admin --account-pass=password --site-name=boo  
  - pwd
  #- cd modules
  #- git clone https://github.com/mohankumargupta/mentionsdrupal8module.git mentionsdrupal8module
  #- drush en -y mentions

before_script:
  - pwd

script:
  - pwd
  - ls -lR 