mentions.mentions:
  type: mapping
  label: 'Mentions'
  mapping:
    input:
      type: mapping
      label: 'Input'
      mapping:
        prefix:
          type: string
          label: 'Prefix'
        suffix:
          type: string
          label: 'Suffix'
    output:
      type: mapping
      label: 'Output'
      mapping:
        prefix:
          type: string
          label: 'Prefix'
        suffix:
          type: string
          label: 'Suffix'  
        text:
          type: string
          label: 'Text'
        link:
          type: string
          label: 'Link'

    mentions:
      type: mapping
      label: 'Mentions'
      mapping:
        id:
          type: string
          label: 'Id'
        name:
          type: string
          label: 'Name'