mentions_type.mentions_type.*:
    type: config_entity
    label: 'Mentions Type'
    mapping:
      id:
        type: string
        label: 'ID'
      label:
        type: label
        label: 'Label'
      uuid:
          type: string

