mentions.mentions_type.*:
  type: config_entity
  label: 'Mentions Type'
  mapping:
    id:
      type: string
      label: 'ID'
    name:
      type: string
      label: 'Name'
    description:
      type: string
      label: 'Description'
    mention_type:
      type: int
      label: 'Mention Type'
    input:
      type: mapping
      label: 'Input Settings'
      mapping:
        prefix:
          type: string
          label: 'Prefix'
        suffix:
          type: string
          label: 'Suffix'
      
      
      
