mentions.mentions_type:
  type: config_entity
  label: 'Mentions Type'
  mapping:
    id:
      type: string
      label: 'ID'
    name:
        type: string
        label: 'Name'
    description:
          type: string
          label: 'Description'

