mentions.mentions:
  type: mapping
  label: 'Mentions Configuration'
  mapping:
    input:
      type: sequence
      sequence:
        - type: string
          label: 'prefix'

        - type: string
          label: 'suffix'
    output:
      type: sequence
      sequence:
        - type: string
          label: 'prefix'
        - type: string
          label: 'suffix'
        - type: string
          label: 'text'
        - type: string
          label: 'link'
    #mentions_events:
    #   type: sequence
    #   label: 'Events'
    #   sequence:
    #     -type: string
    #      label: 'id'
    #     -type: string
    #      label: 'name'
